dict_pais_bandeira = {
    'Inglaterra': 'gb-eng',
    'Suíça': 'ch',
    'Colômbia': 'co',
    'Uruguai': 'uy',
    'Costa do Marfim': 'ci',
    'Argentina': 'ar',
    'México': 'mx',
    'Tunísia': 'tn',
    'Turquia': 'tr',
    'África do Sul': 'za',
    'Canadá': 'ca',
    'Cabo Verde': 'cv',
    'Jordânia': 'jo',
    'Catar': 'qa',
    'Argélia': 'dz',
    'Espanha': 'es',
    'Croácia': 'hr',
    'França': 'fr',
    'Haiti': 'ht',
    'Estados Unidos': 'us',
    'Bósnia': 'ba',
    'Austrália': 'au',
    'Brasil': 'br',
    'Gana': 'gh',
    'Bélgica': 'be',
    'Irã': 'ir',
    'Marrocos': 'ma',
    'Alemanha': 'de',
    'Japão': 'jp',
    'Paraguai': 'py',
    'Panamá': 'pa',
    'Senegal': 'sn',
    'Escócia': 'gb-sct',
    'Coreia do Sul': 'kr',
    'Equador': 'ec',
    'Suécia': 'se',
    'Noruega': 'no',
    'Egito': 'eg',
    'Uzbequistão': 'uz',
    'Arábia Saudita': 'sa',
    'Áustria': 'at',
    'Curaçao': 'cw',
    'Holanda': 'nl',
    'Iraque': 'iq',
    'Nova Zelândia': 'nz',
    'Portugal': 'pt',
    'República Tcheca': 'cz',
    'RD Congo': 'cd'
    }

dias = {
    0: "Segunda",
    1: "Terça",
    2: "Quarta",
    3: "Quinta",
    4: "Sexta",
    5: "Sábado",
    6: "Domingo"
}

dict_jogadores = {'Coreia do Sul': {'Goleiros': ['Kim Seung-gyu',
   'Song Bum-keun',
   'Jo Hyeon-woo'],
  'Defensores': ['Kim Moon-hwan',
   'Kim Min-jae',
   'Kim Tae-hyeon',
   'Park Jin-seob',
   'Seol Young-woo',
   'Jens Castrop',
   'Lee Ki-hyuk',
   'Lee Tae-seok',
   'Lee Han-beom',
   'Cho Yu-min'],
  'Meio-campistas': ['Kim Jing-yu',
   'Bae Jun-ho',
   'Paik Seung-ho',
   'Yang Hyun-jun',
   'Eom Ji-sung',
   'Lee Kang-in',
   'Lee Dong-gyeong',
   'Lee Jae-sung',
   'Hwang In-beom',
   'Hwang Hee-chan'],
  'Atacantes': ['Son Heung-min', 'Oh Hyeon-gyu', 'Cho Gue-sung']},
 'México': {'Goleiros': ['Carlos Acevedo', 'Guillermo Ochoa', 'Raúl Rangel'],
  'Defensores': ['César Montes',
   'Edson Álvarez',
   'Israel Reyes',
   'Jesús Gallardo',
   'Johan Vásquez',
   'Jorge Sánchez',
   'Mateo Chávez'],
  'Meio-campistas': ['Álvaro Fidalgo',
   'Brian Gutiérrez',
   'Luis Romo',
   'Erik Lira',
   'Gilberto Mora',
   'Luis Chávez',
   'Obed Vargas',
   'Orbelín Pineda'],
  'Atacantes': ['Alexis Vega',
   'Armando González',
   'César Huerta',
   'Guillermo Martínez',
   'Julián Quiñones',
   'Raúl Jiménez',
   'Roberto Alvarado',
   'Santiago Giménez']},
 'República Tcheca': {'Goleiros': ['Lukas Hornicek',
   'Matej Kovar',
   'Jindrich Stanek'],
  'Defensores': ['Vladimír Coufal',
   'David Doudera',
   'Tomáš Holeš',
   'Robin Hranac',
   'David Jurásek',
   'Štěpán Chaloupek',
   'Ladislav Krejčí',
   'Jaroslav Zelený',
   'David Zim'],
  'Meio-campistas': ['Lukas Červ',
   'Vladimír Darida',
   'Lukas Provod',
   'Michal Sadilek',
   'Hugo Sochůrek',
   'Alexandr Sojka',
   'Tomáš Souček',
   'Pavel Šulc',
   'Denis Višinský'],
  'Atacantes': ['Adam Hložek',
   'Tomáš Chorý',
   'Mojmír Chytil',
   'Jan Kuchta',
   'Patrik Schick']},
 'África do Sul': {'Goleiros': ['Ronwen Williams',
   'Ricardo Goss',
   'Sipho Chaine'],
  'Defensores': ['Khuliso Mudau',
   'Nkosinathi Sibisi',
   'Ime Okon',
   'Khulumani Ndamane',
   'Aubrey Modiba',
   'Samukelo Kabini',
   'Thabang Matuludi',
   'Olwethu Makhanya',
   'Kamogelo Sebelebele',
   'Bradley Cross',
   'Mbekezeli Mbokazi'],
  'Meio-campistas': ['Teboho Mokoena',
   'Thalente Mbatha',
   'Sphephelo Sithole',
   'Jayden Adams'],
  'Atacantes': ['Oswin Appollis',
   'Iqraam Rayners',
   'Tshepang Moremi',
   'Relebohile Mofokeng',
   'Evidence Makgopa',
   'Themba Zwane',
   'Lyle Foster',
   'Thapelo Maseko']},
 'Bósnia': {'Goleiros': ['Nikola Vasilj',
   'Martin Zlomislic',
   'Osman Hadzikic'],
  'Defensores': ['Kolasinac',
   'Amar Dedic',
   'Nihad Mujakic',
   'Nikola Katic',
   'Tarik Muharemovic',
   'Stjepan Radeljic',
   'Dennis Hadzikadunic',
   'Nidal Celik',
   'Amir Hadziahmetovic',
   'Ivan Sunjic',
   'Ivan Basic',
   'Dzenis Burnic'],
  'Meio-campistas': ['Ermin Mahmic',
   'Benjamin Tahirovic',
   'Amar Memic',
   'Armin Gigovic',
   'Kerim Alajbegovic',
   'Esmir Bajraktrevic'],
  'Atacantes': ['Ermedin Demirovic',
   'Jovo Lukic',
   'Samed Bazdar',
   'Haris Tabakovic',
   'Edin Dzeko']},
 'Canadá': {'Goleiros': ['Dayne St', 'Clair', 'Maxim Crépeau', 'Owen Goodman'],
  'Defensores': ['Alistair Johnston',
   'Derek Cornelius',
   'Richie Laryea',
   'Kiko Sigur',
   'Joel Waterman',
   'Luc de Fougerolles',
   'Moise Bombito',
   'Alfie Jones',
   'Alphonso Davies'],
  'Meio-campistas': ['Stephen Eustáquio',
   'Ismael Koné',
   'Tajon Buchanan',
   'Mathieu Choinière',
   'Ali Ahmed',
   'Nathan Saliba',
   'Liam Millar',
   'Marcelo Flores',
   'Jacob Shaffelburg',
   'Jonathan Osorio'],
  'Atacantes': ['Jonathan David',
   'Cyle Larin',
   'Tani Oluwaseyi',
   'Promise David']},
 'Catar': {'Goleiros': ['Shehab El-Leithy',
   'Salah Zakaria',
   'Meshaal Barsham',
   'Mahmoud Abundi'],
  'Defensores': ['Boualem Khoukhi',
   'Pedro Miguel',
   'Sultan Al-Buraik',
   'Tarek Salman',
   'Ahmed Al-Janahi',
   'Ahmed Alaa',
   'Al-Hashemi Al-Hussain',
   'Ayoub Al-Alawi',
   'Bassam Al-Rawi',
   'Rayan Al-Ali',
   'Issa Laye',
   'Lucas Mendes',
   'Mohammed Waad',
   'Niall Mason',
   'Humam Al-Amin',
   'Youssef Abdulrazaq'],
  'Meio-campistas': ['Ahmed Fathi',
   'Tahseen Mohammed',
   'Jassim Jaber',
   'Hassan Al-Haydos',
   'Assim Madibo',
   'Abdulaziz Hatem',
   'Karim Boudiaf',
   'Mohammed Manaei'],
  'Atacantes': ['Edmilson Junior',
   'Akram Afif',
   'Almoez Ali',
   'Sebastian Soria',
   'Mubarak Shannan',
   'Mohammed Muntari']},
 'Suíça': {'Goleiros': ['Marvin Keller', 'Gregor Kobel', 'Yvon Mvogo'],
  'Defensores': ['Manuel Akanji',
   'Aurele Amenda',
   'Eray Comert',
   'Nico Elvedi',
   'Luca Jaquez',
   'Miro Muheim',
   'Ricardo Rodriguez',
   'Silvan Widmer'],
  'Meio-campistas': ['Michel Aebischer',
   'Christian Fassnacht',
   'Remo Freuler',
   'Ardon Jashari',
   'Johan Manzambi',
   'Fabian Rieder',
   'Djibril Sow',
   'Ruben Vargas',
   'Granit Xhaka',
   'Denis Zakaria'],
  'Atacantes': ['Zeki Amdouni',
   'Breel Embolo',
   'Cedric Itten',
   'Dan Ndoye',
   'Noah Okafor']},
 'Brasil': {'Goleiros': ['Alisson (Liverpool)',
   'Ederson (Fenerbahçe)',
   'Weverton (Grêmio)'],
  'Defensores': ['Alex Sandro (Flamengo)',
   'Bremer (Juventus)',
   'Danilo (Flamengo)',
   'Douglas Santos (Zenit)',
   'Gabriel Magalhães (Arsenal)',
   'Ibañez (Al-Ahli)',
   'Léo Pereira (Flamengo)',
   'Marquinhos (PSG)'],
  'Meio-campistas': ['Bruno Guimarães (Newcastle)',
   'Casemiro (Manchester United)',
   'Danilo Santos (Botafogo)',
   'Fabinho (Al-Ittihad)',
   'Lucas Paquetá (Flamengo)',
   'Ederson (Manchester United)'],
  'Atacantes': ['Endrick (Lyon)',
   'Gabriel Martinelli (Arsenal)',
   'Igor Thiago (Brentford)',
   'Luiz Henrique (Zenit)',
   'Matheus Cunha (Manchester United)',
   'Neymar (Santos)',
   'Raphinha (Barcelona)',
   'Rayan (Bournemouth)',
   'Vini Jr',
   '(Real Madrid)']},
 'Escócia': {'Goleiros': ['Craig Gordon', 'Angus Gunn', 'Liam Kelly'],
  'Defensores': ['Grant Hanley',
   'Jack Hendry',
   'Aaron Hickey',
   'Dom Hyam',
   'Scott McKeena',
   'Nathan Patterson',
   'Anthony Ralston',
   'Andy Robertson',
   'John Souttar',
   'Kieran Tierney'],
  'Meio-campistas': ['Ryan Christie',
   'Findlay Curtis',
   'Lewis Ferguson',
   'Bem Gannon-Doak',
   'Billy Gilmour',
   'John McGinn',
   'Kenny McLrean',
   'Scott McTominay'],
  'Atacantes': ['Ché Adams',
   'Lyndon Dykes',
   'George Hisrt',
   'Lawrence Shankland',
   'Ross Stewart']},
 'Haiti': {'Goleiros': ['Johnny Placide',
   'Alexandre Pierre',
   'Josué Duverger'],
  'Defensores': ['Carlens Arcus',
   'Wilguens Pauguain',
   'Duke Lacroix',
   'Martin Experience',
   'JK Duverne',
   'Ricardo Ade',
   'Hannes Delcroix',
   'Keeto Thermoncy'],
  'Meio-campistas': ['Leverton Pierre',
   'Carl-Fred Sainthe',
   'Jean-Jacques Danley',
   'Jeanricner Bellegarde',
   'Pierre Woodenski',
   'Dominique Simon'],
  'Atacantes': ['Louicius Deedson',
   'Ruben Providence',
   'Josué Casimir',
   'Derrick Etienne',
   'Wilson Isidor',
   'Duckens Nazon',
   'Frantzdy Pierrot',
   'Yassin Fortune',
   'Lenny Joseph']},
 'Marrocos': {'Goleiros': ['Yassine Bounou',
   'Munir El Kajoui',
   'Ahmed Reda Tagnaouti'],
  'Defensores': ['Achraf Hakimi',
   'Noussair Mazraoui',
   'Anass Salah-Eddine',
   'Youssef Belammari',
   'Nayef Aguerd',
   'Issa Diop',
   'Chadi Riad',
   'Redouane Halhal',
   'Zakaria El Ouahdi'],
  'Meio-campistas': ['Azzedine Ounahi',
   'Neil El Aynaoui',
   'Sofyan Amrabat',
   'Ayoub Bouaddi',
   'Samir El Mourabet',
   'Bilal El Khannouss',
   'Ismaël Saibari'],
  'Atacantes': ['Brahim Díaz',
   'Abdessamad Ezzalzouli',
   'Yassine Bessime',
   'Chemsdine Talbi',
   'Soufiane Rahimi',
   'Ayoub El Kaabi',
   'Ayoubе Amahount']},
 'Austrália': {'Goleiros': ['Patrick Beach', 'Paul Izzo', 'Maty Ryan'],
  'Defensores': ['Aziz Behich',
   'Jordan Bos',
   'Cameron Burgess',
   'Alessandro Circati',
   'Milos Degenek',
   'Jason Geria',
   'Lucas Herrington',
   'Jacob Italiano',
   'Harry Souttar',
   'Kai Trewin'],
  'Meio-campistas': ['Cameron Devlin',
   'Ajdin Hrustic',
   'Jackson Irvine',
   'Connor Metcalfe',
   'Paul Okon-Engstler',
   "Aiden O'Neill"],
  'Atacantes': ['Nestory Irankunda',
   'Mathew Leckie',
   'Awer Mabil',
   'Mohamed Toure',
   'Nishan Velupillay',
   'Cristian Volpato',
   'Tete Yengi']},
 'Estados Unidos': {'Goleiros': ['Chris Brady', 'Matt Freese', 'Matt Turner'],
  'Defensores': ['Max Arfsten',
   'Sergiño Dest',
   'Alex Freeman',
   'Mark McKenzie',
   'Tim Ream',
   'Chris Richards',
   'Antonee Robinson',
   'Miles Robinson',
   'Joe Scally',
   'Auston Trusty'],
  'Meio-campistas': ['Tyler Adams',
   'Sebastian Berhalter',
   'Weston McKennie',
   'Cristian Roldan'],
  'Atacantes': ['Folarin Balogun',
   'Ricardo Pepi',
   'Haji Wright',
   'Brenden Aaronson',
   'Christian Pulisic',
   'Gio Reyna',
   'Malik Tillman',
   'Tim Weah',
   'Alejandro Zendejas']},
 'Paraguai': {'Goleiros': ['Gastón Olveira',
   'Roberto Jr',
   'Fernández',
   'Orlando Gill'],
  'Defensores': ['Juan Cáceres',
   'Junior Alonso',
   'Alexandro Maidana',
   'Gustavo Gómez',
   'Fabián Balbuena',
   'Gustavo Velázquez',
   'Omar Alderete',
   'José Canale'],
  'Meio-campistas': ['Andrés Cubas',
   'Diego Gómez',
   'Matías Galarza',
   'Damián Bobadilla',
   'Braian Ojeda',
   'Mauricio'],
  'Atacantes': ['Julio Enciso',
   'Alejandro Romero Gamarra',
   'Miguel Almirón',
   'Gustavo Caballero',
   'Ramón Sosa',
   'Antonio Sanabria',
   'Gabriel Ávalos',
   'Alex Arce',
   'Isidro Pitta']},
 'Turquia': {'Goleiros': ['Altay Bayindir', 'Mert Gunok', 'Ugurcan Cakir'],
  'Defensores': ['Abdulkerim Bardakci',
   'Caglar Soyuncu',
   'Eren Elmali',
   'Ferdi Kadioglu',
   'Merih Demiral',
   'Mert Muldur',
   'Ozan Kabak',
   'Samet Akaydin',
   'Zeki Celik'],
  'Meio-campistas': ['Hakan Calhanoglu',
   'Ismail Yuksek',
   'Kaan Ayhan',
   'Orkun Kokcu',
   'Salih Ozcan'],
  'Atacantes': ['Arda Guler',
   'Baris Alper Yilmaz',
   'Can Uzun',
   'Deniz Gul',
   'Irfan Can Kahveci',
   'Kenan Yildiz',
   'Kerem Akturkoglu',
   'Oguz Aydin',
   'Yunus Akgun']},
 'Alemanha': {'Goleiros': ['Oliver Baumann',
   'Manuel Neuer',
   'Alexander Nubel'],
  'Defensores': ['Waldemar Anton',
   'Nathaniel Brown',
   'Pascal Grob',
   'Joshua Kimmich',
   'Felix Nmecha',
   'Aleksandar Pavlovic',
   'David Raum',
   'Antonio Rudiger',
   'Nico Schlotterbeck',
   'Angelo Stiller',
   'Jonathan Tah',
   'Malick Thiaw'],
  'Meio-campistas': ['Aleksandar Pavlovic',
   'Joshua Kimmich',
   'Leon Goretzka',
   'Jamie Leweling',
   'Jamal Musiala',
   'Pascal Gross',
   'Angelo Stiller',
   'Florian Wirtz',
   'Leroy Sané',
   'Nadiem Amiri',
   'Felix Nmecha',
   'Lennart Karl'],
  'Atacantes': ['Kai Havertz',
   'Nick Woltemade',
   'Maximilian Beier',
   'Deniz Undav']},
 'Costa do Marfim': {'Goleiros': ['Yahia Fofana',
   'Mohamed Koné',
   'Alban Lafont'],
  'Defensores': ['Emmanuel Agbadou',
   'Clement Akpa',
   'Ousmane Diomande',
   'Guela Doue',
   'Ghislain Konan',
   'Odilon Kossounou',
   'Evan Ndicka',
   'Wilfried Singo'],
  'Meio-campistas': ['Seko Fofana',
   'Parfait Guiagon',
   'Christ Inao Dulai',
   'Franck Kessié',
   'Ibrahim Sangare',
   'Jean-Mickael Seri'],
  'Atacantes': ['Simon Adingra',
   'Ange-voan Bonny',
   'Amad Diallo',
   'Oumar Diakité',
   'Van Diomande',
   'Evann Guessand',
   'Nicolas Pepé',
   'Bazoumana Touré',
   'Elye Wahi']},
 'Curaçao': {'Goleiros': ['Tyrick Bodak', 'Trevor Doornbusch', 'Eloy Room'],
  'Defensores': ['Riechedly Bazoer',
   'Joshua Brenet',
   'Sherel Floranus',
   'Deveron Fonville',
   'Juriën Gaari',
   'Armando Obispo',
   'Shurandy Sambo',
   'Roshon van Eijma'],
  'Meio-campistas': ['Juninho Bacuna',
   'Leandro Bacuna',
   'Livano Comenencia',
   'Kevin Felida',
   'Arjany Martha',
   'Tyrese Noslin',
   'Godfried Roemeratoe'],
  'Atacantes': ['Jeremy Antonisse',
   'Tahith Chong',
   'Kenji Gorre',
   'Sontje Hansen',
   'Gervane Kastaneer',
   'Brandley Kuwas',
   'Jürgen Locadia',
   'Jearl Margaritha']},
 'Equador': {'Goleiros': ['Hernán Galíndez',
   'Moisés Ramírez',
   'Gonzalo Valle'],
  'Defensores': ['Piero Hincapie',
   'Willian Pacho',
   'Pervis Estupinan',
   'Felix Torres',
   'Joel Ordonez',
   'Jackson Porozo',
   'Angelo Preciado'],
  'Meio-campistas': ['Moises Caicedo',
   'Alan Franco',
   'Kendry Paez',
   'Pedro Vite',
   'Jordy Alcivar',
   'Denil Castillo',
   'Yaimar Medina'],
  'Atacantes': ['Enner Valencia',
   'Gonzalo Plata',
   'Alan Minda',
   'John Yeboah',
   'Kevin Rodriguez',
   'Jordy Caicedo',
   'Nilson Angulo',
   'Anthony Valencia',
   'Jeremy Arevalo']},
 'Holanda': {'Goleiros': ['Verbruggen', 'Flekken', 'Roefs'],
  'Defensores': ['Dumfries',
   'Wieffer',
   'Van Dijk',
   'Van Hecke',
   'Jurriën Timber',
   'Aké',
   'Van de Ven',
   'Hato'],
  'Meio-campistas': ['De Jong',
   'Reijnders',
   'Gravenberch',
   'Koopmeiners',
   'Justin Kluivert',
   'De Roon',
   'Quinten Timber',
   'Til'],
  'Atacantes': ['Memphis Depay',
   'Gakpo',
   'Malen',
   'Summerville',
   'Noa Lang',
   'Weghorst',
   'Brobbey']},
 'Japão': {'Goleiros': ['Zion Suzuki', 'Tomoki Hayakawa', 'Keisuke Osako'],
  'Defensores': ['Yuto Nagatomo',
   'Shogo Taniguchi',
   'Ko Itakura',
   'Tsuyoshi Watanabe',
   'Takehiro Tomiyasu',
   'Hiroki Ito',
   'Ayumu Seko',
   'Yukinari Sugawara',
   'Junnoske Suzuki'],
  'Meio-campistas': ['Wataru Endo',
   'Junya Ito',
   'Daichi Kamada',
   'Ritsu Doan',
   'Ao Tanaka',
   'Keito Nakamura',
   'Kaishu Sano',
   'Takefusa Kubo'],
  'Atacantes': ['Koki Ogawa',
   'Daizen Maeda',
   'Ayase Ueda',
   'Yuito Suzuki',
   'Kento Shoigai',
   'Keisuke Goto']},
 'Suécia': {'Goleiros': ['Kristoffer Nordfeldt',
   'Viktor Johansson',
   'Jacob Widell Zetterstrom'],
  'Defensores': ['Daniel Svensson',
   'Victor Nilsson Lindelof',
   'Emil Holm',
   'Isak Hien',
   'Carl Starfelt',
   'Gustavo Lagerbielke',
   'Gabriel Gudmundsson',
   'Hjalmar Ekdal',
   'Elliot Stroud',
   'Eric Smith'],
  'Meio-campistas': ['Taha Ali',
   'Yasin Ayari',
   'Lucas Bergvall',
   'Jesper Karlstrom',
   'Benjamin Nygren',
   'Mattias Svanberg',
   'Besfort Zeneli'],
  'Atacantes': ['Alexander Bernhardsson',
   'Anthony Elanga',
   'Viktor Gyökeres',
   'Alexandre Isak',
   'Gustavo Nilsson',
   'Ken Sema']},
 'Tunísia': {'Goleiros': ['Sabri Ben Hessen',
   'Abdelmouhib Chamakh',
   'Aymen Dahman'],
  'Defensores': ['Ali Abdi',
   'Adem Arous',
   'Mohamed Amine Ben Hamida',
   'Dylan Bronn',
   'Raed Chikhaoui',
   'Moutaz Neffati',
   'Omar Rekik',
   'Montassar Talbi',
   'Yan Valery'],
  'Meio-campistas': ['Mortadha Ben Ouanes',
   'Anis Ben Slimane',
   'Ismael Gharbi',
   'Rani Khedira',
   'Mohamed Hadj Mahmoud',
   'Hannibal Mejbri',
   'Ellyes Skhiri'],
  'Atacantes': ['Elias Achouri',
   'Khalil Ayari',
   'Firas Chaouat',
   'Rayan Elloumi',
   'Hazem Mastouri',
   'Elias Saad',
   'Sebastian Tounekti']},
 'Bélgica': {'Goleiros': ['Thibaut Courtois', 'Senne Lammens', 'Mike Penders'],
  'Defensores': ['Timothy Castagne',
   'Zeno Debast',
   'Maxim De Cuyper',
   'Koni De Winter',
   'Brandon Mechele',
   'Thomas Meunier',
   'Nathan Ngoy',
   'Joaquin Seys',
   'Arthur Theate'],
  'Meio-campistas': ['Kevin De Bruyne',
   'Amadou Onana',
   'Nicolas Raskin',
   'Youri Tielemans',
   'Hans Vanaken',
   'Axel Witsel'],
  'Atacantes': ['Charles De Ketelaere',
   'Jeremy Doku',
   'Matias Fernandez-Pardo',
   'Romelu Lukaku',
   'Dodi Lukebakio',
   'Diego Moreira',
   'Alexis Saelemaekers',
   'Leandro Trossard']},
 'Egito': {'Goleiros': ['Mohamed El Shenawy',
   'Mostafa Shobeir',
   'El Mahdi Soliman',
   'Mohamed AlaMohamed Hani'],
  'Defensores': ['Tarek Hamed',
   'Hamdi Fathy',
   'Ramy Rabia',
   'Yasser Ibrahim',
   'Hossam Abdel-Maguid',
   'Mohamed Abdel-Moniem',
   'Ahmed Fotouh',
   'Karim Hafez'],
  'Meio-campistas': ['Marwan Attia',
   'Mohand Lashin',
   'Nabil Emad Dunga',
   'Mahmoud Saber',
   'Ahmed Sayed Zizo',
   'Imam Ashour',
   'Mostafa Abdel-Raouf Ziko',
   'Mahmoud Trezeguet',
   'Ibrahim Adel',
   'Haithem Hassan',
   'Mohamed Salah'],
  'Atacantes': ['Omar Marmoush', 'Akram Tawfiq', 'Hamza Abdel-Karim']},
 'Irã': {'Goleiros': ['Alireza Beiranvand',
   'Seyed Hossein Hosseini',
   'Payam Niazmand'],
  'Defensores': ['Danial Eiri',
   'Ehsan Hajsafi',
   'Saleh Hardani',
   'Hossein Kanaani',
   'Shoja Khalilzadeh',
   'Milad \u2060Mohammadi',
   '\u200bAli Nemati',
   'Ramin Rezaeian'],
  'Meio-campistas': ['Rouzbeh Cheshmi',
   'Saeid Ezatolahi',
   'Mehdi \u200bGhaedi',
   'Saman Ghoddos',
   'Mohammad Ghorbani',
   'Alireza Jahanbakhsh',
   'Mohammad Mohebi',
   'Amir Mohammad Razzaghinia',
   'Mehdi Torabi',
   'Aria Yousefi'],
  'Atacantes': ['Ali Alipour',
   'Dennis Dargahi',
   'Amirhossein Hosseinzadeh',
   'Mehdi Taremi',
   'Shahriar Moghanlou']},
 'Nova Zelândia': {'Goleiros': ['Max Crocombe',
   'Alex Paulsen',
   'Michael Woud'],
  'Defensores': ['Tyler Bindon',
   'Michael Boxall',
   'Liberato Cacace',
   'Francis de Vries',
   'Callan Elliot',
   'Tim Payne',
   'Nando Pijnaker',
   'Tommy Smith',
   'Finn Surman'],
  'Meio-campistas': ['Lachlan Bayliss',
   'Joe Bell',
   'Matt Garbett',
   'Ben Old',
   'Alex Rufer',
   'Sarpreet Singh',
   'Marko Stamenic',
   'Ryan Thomas'],
  'Atacantes': ['Kosta Barbarouses',
   'Eli Just',
   'Callum McCowatt',
   'Jesse Randall',
   'Ben Waine',
   'Chris Wood']},
 'Arábia Saudita': {'Goleiros': ['Ahmed Al Kassar',
   'Mohammed Al Owais',
   'Nawaf Al Aqidi'],
  'Defensores': ['Saud Abdulhamid',
   'Mohammed Abu Al Shamat',
   'Khalid Al Ghannam',
   'Moteb Al Harbi',
   'Abdulelah Al Amri',
   'Nawaf Boushal',
   'Hassan Kadesh',
   'Ali Lajami',
   'Ali Majrashi',
   'Hassan Tambakti',
   'Jehad Thikri'],
  'Meio-campistas': ['Nasser Al Dawsari',
   'Alaa Al Hajji',
   'Ziyad Al Johani',
   'Musab Al Juwayr',
   'Abdullah Al Khaibari',
   'Mohammed Kanno',
   'Sultan Mandash',
   'Ayman Yahya'],
  'Atacantes': ['Feras Al Brikan',
   'Salem Al Dawsari',
   'Abdullah Al Hamdan',
   'Saleh Al Shehri']},
 'Cabo Verde': {'Goleiros': ['Carlos dos Santos', 'Márcio Rosa', 'Vozinha'],
  'Defensores': ['Sidny Cabral',
   'Diney Borges',
   'Logan Costa',
   'Roberto Lopes',
   'Steven Moreira',
   'Wagner Pina',
   'Kelvin Pires',
   'Stopira'],
  'Meio-campistas': ['Telmo Arcanjo',
   'Deroy Duarte',
   'Laros Duarte',
   'João Paulo Fernandes',
   'Jamiro Monteiro',
   'Kevin Pina',
   'Yannick Semedo'],
  'Atacantes': ['Gilson Benchimol',
   'Jovane Cabral',
   'Dailon Livramento',
   'Ryan Mendes',
   'Nuno da Costa',
   'Garry Rodrigues',
   'Willy Semedo',
   'Hélio Varela']},
 'Espanha': {'Goleiros': ['Unai Simón', 'David Raya', 'Joan García'],
  'Defensores': ['Marc Cucurella',
   'Alex Grimaldo',
   'Pau Cubarsí',
   'Laporte',
   'Pubill',
   'Eric García',
   'Marcos Llorente',
   'Pedro Porro'],
  'Meio-campistas': ['Pedri',
   'Fabián Ruiz',
   'Zubimendi',
   'Gavi',
   'Rodri',
   'Alex Baena',
   'Mikel Merino'],
  'Atacantes': ['Oyarzabal',
   'Dani Olmo',
   'Nico Williams',
   'Yeremy Pino',
   'Ferran Torres',
   'Borja Iglesias',
   'Víctor Muñoz',
   'Lamine Yamal']},
 'Uruguai': {'Goleiros': ['Sergio Rochet',
   'Fernando Muslera',
   'Santiago Mele'],
  'Defensores': ['Guillermo Varela',
   'Ronald Araujo',
   'José María Giménez',
   'Santiago Bueno',
   'Sebastián Cáceres',
   'Mathías Olivera',
   'Joaquín Piquerez',
   'Matías Viña'],
  'Meio-campistas': ['Juan Manuel Sanabria',
   'Manuel Ugarte',
   'Emiliano Martínez',
   'Rodrigo Bentancur',
   'Federico Valverde',
   'Giorgian de Arrascaeta',
   'Nicolás de la Cruz',
   'Rodrigo Zalazar',
   'Agustín Canobbio',
   'Facundo Pellistri',
   'Maxi Araújo',
   'Brian Rodríguez'],
  'Atacantes': ['Rodrigo Aguirre', 'Federico Viñas', 'Darwin Núñez']},
 'França': {'Goleiros': ['Mike Maignan', 'Robin Risser', 'Brice Samba'],
  'Defensores': ['Lucas Digne',
   'Malo Gusto',
   'Lucas Hernandez',
   'Theo Hernandez',
   'Ibrahima Konaté',
   'Jules Koundé',
   'Maxence Lacroix',
   'William Saliba',
   'Dayot Upamecano'],
  'Meio-campistas': ["N'Golo Kanté",
   'Manu Koné',
   'Adrien Rabiot',
   'Aurélien Tchouaméni',
   'Warren Zaïre-Emery'],
  'Atacantes': ['Maghnes Akliouche',
   'Bradley Barcola',
   'Rayan Cherki',
   'Ousmane Dembélé',
   'Désiré Doué',
   'Jean-Philippe Mateta',
   'Kylian Mbappé',
   'Michael Olise',
   'Marcus Thuram']},
 'Iraque': {'Goleiros': ['Fahad Talib', 'Jalal Hassan', 'Ahmed Basil'],
  'Defensores': ['Hussein Ali',
   'Manaf Younis',
   'Zaid Tahseen',
   'Rebin Sulaka',
   'Akam Hashem',
   'Merchas Doski',
   'Ahmed Yahya',
   'Zaid Ismail',
   'Frans Putros',
   'Mustafa Saadoon'],
  'Meio-campistas': ['Amir Al Ammari',
   'Kevin Yakob',
   'Zidane Iqbal',
   'Aimar Sher',
   'Ibrahim Bayesh',
   'Ahmed Qasim',
   'Youssef Amyn',
   'Marko Farji'],
  'Atacantes': ['Ali Jassim',
   'Ali Al Hamadi',
   'Ali Yousef',
   'Aymen Hussein',
   'Mohanad Ali']},
 'Noruega': {'Goleiros': ['Orjan Nyland', 'Egil Selvik', 'Tangvik'],
  'Defensores': ['Kristoffer Ajer',
   'Torbjorn Heggem',
   'Leo Skiri Ostigard',
   'Sondre Langas',
   'Henrik Falchener',
   'Julian Ryerson',
   'Marcus Holmgren Pedersen',
   'David Moller Wolfe',
   'Fredrik Bjorkan'],
  'Meio-campistas': ['Martin Odegaard',
   'Sander Berge',
   'Fredrik Aursnes',
   'Patrick Berg',
   'Kristian Thorstvedt',
   'Thelonious Asgard',
   'Morten Thorsby'],
  'Atacantes': ['Erling Haaland',
   'Alexander Sorloth',
   'Jorgen Strand Larsen',
   'Antonio Nusa',
   'Oscar Bobb',
   'Andreas Schjelderup',
   'Jans Petter Hauge']},
 'Senegal': {'Goleiros': ['Edouard Mendy', 'Yehvann Diouf', 'Mory Diaw'],
  'Defensores': ['Krepin Diatta',
   'Antoine Mendy',
   'Abdoulaye Seck',
   'Kalidou Koulibaly',
   'Moussa Niakhate',
   'Mamadou Sarr',
   'El-Hadji Malick Diouf',
   'Ismail Jakobs'],
  'Meio-campistas': ['Idrissa Gueye',
   'Habib Diarra',
   'Pape Matar Sarr',
   'Pape Gueye',
   'Lamine Camara',
   'Pathe Ciss',
   'Bara Ndiaye'],
  'Atacantes': ['Sadio Mane',
   'Bamba Dieng',
   'Iliman Ndiaye',
   'Nicolas Jackson',
   'Assane Diao',
   'Ibrahim Mbaye',
   'Cherif Ndiaye',
   'Ismaila Sarr']},
 'Argentina': {'Goleiros': ['Musso', 'Rulli', 'Dibu Martínez'],
  'Defensores': ['Balerdi',
   'Tagliafico',
   'Montiel',
   'Lisandro Martínez',
   'Romero',
   'Otamendi',
   'Medina',
   'Molina'],
  'Meio-campistas': ['Paredes',
   'De Paul',
   'Barco',
   'Lo Celso',
   'Palacios',
   'MacAllister',
   'Enzo Fernández'],
  'Atacantes': ['Julián Álvarez',
   'Lionel Messi',
   'Nico González',
   'Thiago Almada',
   'Giuliano Simeone',
   'Nico Paz',
   'Flaco López',
   'Lautaro Martínez']},
 'Argélia': {'Goleiros': ['Oussama Benbot', 'Melvin Masstil', 'Luca Zidane'],
  'Defensores': ['Achraf Abada',
   'Rayan Ait Nouri',
   'Zinedine Belaid',
   'Rafik Belghali',
   'Ramy Bensebaini',
   'Samir Chergui',
   'Jaouen Hadjam',
   'Aissa Mandi',
   'Mohamed Amine Tougai'],
  'Meio-campistas': ['Houssem Aouar',
   'Nabil Bentaleb',
   'Hicham Boudaoui',
   'Fares Chaibi',
   'Ibrahim Maza',
   'Yassine Titraoui',
   'Ramiz Zerrouki'],
  'Atacantes': ['Mohamed Amine Amoura',
   'Nadir Benbouali',
   'Adil Boulbina',
   'Fares Ghedjemis',
   'Amine Gouiri',
   'Riyad Mahrez',
   'Anis Hadj Moussa']},
 'Áustria': {'Goleiros': ['Alexander Schlager',
   'Florian Wiegele',
   'Patrick Pentz'],
  'Defensores': ['David Affengruber',
   'Kevin Danso',
   'Stefan Posch',
   'David Alaba',
   'Philipp Lienhart',
   'Phillipp Mwene',
   'Alexander Prass',
   'Marco Friedl',
   'Michael Svoboda'],
  'Meio-campistas': ['Xaver Schlager',
   'Nicolas Seiwald',
   'Marcel Sabitzer',
   'Florian Grillitsch',
   'Carney Chukwuemeka',
   'Romano Schmid',
   'Christoph Baumgartner',
   'Konrad Laimer',
   'Patrick Wimmer',
   'Paul Wanner',
   'Alessandro Schopf'],
  'Atacantes': ['Marko Arnautović', 'Michael Gregoritsch', 'Sasa Kalajdzic']},
 'Jordânia': {'Goleiros': ['Yazeed Abu Laila',
   'Abdullah Al-Fakhouri',
   'Nour Bani Attiah'],
  'Defensores': ['Abdallah Nasib',
   'Saed Al-Rosan',
   'Yazan Al-Arab',
   'Saleem Obaid',
   'Mohammad Abualnadi',
   'Husam Abu Dahab',
   'Ihsan Haddad',
   'Anas Badawi',
   'Mohannad Abu Taha',
   'Mohammad Abu Hashish'],
  'Meio-campistas': ['Nour Al-Rawabdeh',
   'Nizar Al-Rashdan',
   'Ibrahim Sadeh',
   'Rajaei Ayed',
   'Amer Jamous',
   'Mohammad Al-Dawoud'],
  'Atacantes': ['Mahmoud Al-Mardi',
   'Musa Al-Taamari',
   'Mohammad Abu Zrayq',
   'Ali Al-Azaizeh',
   'Ibrahim Sabra',
   'Ali Olwan']},
 'Colômbia': {'Goleiros': ['Camilo Vargas', 'Alvaro Montero', 'David Ospina'],
  'Defensores': ['Davinson Sánchez',
   'Jhon Lucumí',
   'Yerry Mina',
   'Daniel Muñoz',
   'Willer Ditta',
   'Santiago Arias',
   'Johan Mojica',
   'Deiver Machado'],
  'Meio-campistas': ['Richard Ríos',
   'Jefferson Lerma',
   'Kevin Castaño',
   'Gustavo Puerta',
   'Jhon Arias',
   'Jorge Carrascal',
   'Juan Portilla',
   'Juan Quintero',
   'James Rodríguez',
   'Jaminton Campaz'],
  'Atacantes': ['Cucho Hernández',
   'Luis Díaz',
   'Luis Suárez',
   'Andrés Gómez',
   'Jhon Córdoba']},
 'Portugal': {'Goleiros': ['Diogo Costa',
   'José Sá',
   'Rui Silva',
   'Ricardo Velho'],
  'Defensores': ['Diogo Dalot',
   'Matheus Nunes',
   'Nelson Semedo',
   'João Cancelo',
   'Nuno Mendes',
   'Gonçalo Inácio',
   'Renato Veiga',
   'Ruben Dias',
   'Tomás Araújo'],
  'Meio-campistas': ['Ruben Neves',
   'Samu Costa',
   'João Neves',
   'Vitinha',
   'Bruno Fernandes',
   'Bernardo Silva'],
  'Atacantes': ['João Félix',
   'Francisco Trincão',
   'Francisco Conceição',
   'Pedro Neto',
   'Rafael Leão',
   'Gonçalo Guedes',
   'Gonçalo Ramos',
   'Cristiano Ronaldo']},
 'RD Congo': {'Goleiros': ['Matthieu Epolo', 'Timothy Fayulu', 'Lionel Mpasi'],
  'Defensores': ['Dylan Batubinsika',
   'Aaron Tshibola',
   'Gedoon Kalulu',
   'Steve Kapuadi',
   'Joris Kayembe',
   'Arthur Masuaku',
   'Chancel Mbemba',
   'Axel Tuanzebe',
   'Aaron Wan-Bissaka'],
  'Meio-campistas': ['Theo Bongonda',
   'Brian Cipenga',
   'Meshack Elia',
   'Gael Kakuta',
   'Edo Kayembe',
   'Nathanael Mbuku',
   'Samuel Moutoussamy',
   "Ngal'ayel Mukau",
   'Charles Pickel',
   'Noah Sadiki'],
  'Atacantes': ['Cedric Bakambu',
   'Simon Banza',
   'Fiston Mayele',
   'Yoane Wissa']},
 'Uzbequistão': {'Goleiros': ['Utkir Yusupov',
   'Botirali Ergashev',
   'Abduvokhid Nematov'],
  'Defensores': ['Abdukodir Khusanov',
   'Khozhiakbar Alizhonov',
   'Farrukh Sayfiev',
   'Rustam Ashurmatov',
   'Sherzod Nasrullaev',
   'Umar Eshmurodov',
   'Avazbek Ulmasaliev',
   'Jakhongir Urozov',
   'Bekhruz Karimov',
   'Abdulla Abdullaev'],
  'Meio-campistas': ['Akmal Mozgovoy',
   'Otabek Shukurov',
   'Jamshid Iskanderov',
   'Odildzhon Khamrobekov',
   'Jaloliddin Masharipov',
   'Aziz Ganiev',
   'Sherzod Esanov',
   'Abbosbek Fayzullaev'],
  'Atacantes': ['Eldor Shomurodov',
   'Igor Sergeev',
   'Azizbek Amanov',
   'Oston Urunov',
   'Dostonbek Khamdamov']},
 'Croácia': {'Goleiros': ['Dominik Livakovic',
   'Dominik Kotarski',
   'Ivor Pandur'],
  'Defensores': ['Josko Gvardiol',
   'Duje Caleta-Car',
   'Josip Sutalo',
   'Josip Stanisic',
   'Marin Pongracic',
   'Martin Erlic',
   'Luka Vuskovic'],
  'Meio-campistas': ['Luka Modric',
   'Mateo Kovacic',
   'Mario Pasalic',
   'Nikola Vlasic',
   'Luka Sucic',
   'Martin Baturina',
   'Kristijan Jakic',
   'Petar Sucic',
   'Nikola Moro',
   'Toni Fruk'],
  'Atacantes': ['Ivan Perisic',
   'Andrej Kramaric',
   'Ante Budimir',
   'Marco Pasalic',
   'Peter Musa',
   'Igor Matanovic']},
 'Gana': {'Goleiros': ['Joseph Anang', 'Benjamin Asare', 'Lawrence Ati-Zigi'],
  'Defensores': ['Jonas Adjetey',
   'Derrick Luckassen',
   'Gideon Mensah',
   'Abdul Mumin',
   'Jerome Opoku',
   'Kojo Oppong Preprah',
   'Baba Abdul Rahman',
   'Alidu Seidu',
   'Marvin Senaya'],
  'Meio-campistas': ['Augustine Boakye',
   'Abdul Fatawu Issahaku',
   'Elisha Owusu',
   'Thomas Partey',
   'Kwasi Sibo',
   'Kamal Deen Sulemana',
   'Caleb Yirenkyi'],
  'Atacantes': ['Príncipe Kwabena Adu',
   'Jordan Ayew',
   'Christopher Bonsu Baah',
   'Ernest Nuamah',
   'Antoine Semenyo',
   'Brandon Thomas-Asante',
   'Inaki Williams']},
 'Inglaterra': {'Goleiros': ['Jordan Pickford',
   'Dean Henderson',
   'James Trafford'],
  'Defensores': ['Reece James',
   'Ezri Konsa',
   'Jarell Quansah',
   'John Stones',
   'Marc Guehi',
   'Dan Burn',
   "Nico O'Reilly",
   'Djed Spence',
   'Tino Livramento'],
  'Meio-campistas': ['Declan Rice',
   'Elliot Anderson',
   'Kobbie Mainoo',
   'Jordan Henderson',
   'Morgan Rogers',
   'Jude Bellingham',
   'Eberechi Eze'],
  'Atacantes': ['Harry Kane',
   'Ivan Toney',
   'Ollie Watkins',
   'Bukayo Saka',
   'Marcus Rashford',
   'Anthony Gordon',
   'Noni Madueke']},
 'Panamá': {'Goleiros': ['Orlando Mosquera', 'Luis Mejía', 'César Samudio'],
  'Defensores': ['César Blackman',
   'Jorge Gutiérrez',
   'Amir Murillo',
   'Fidel Escobar',
   'Andrés Andrade',
   'Edgardo Fariña',
   'José Córdoba',
   'Eric Davis',
   'Jiovany Ramos',
   'Roderick Miller'],
  'Meio-campistas': ['Aníbal Godoy',
   'Adalberto Carrasquilla',
   'Carlos Harvey',
   'Cristian Martínez',
   'José Luis Rodríguez',
   'César Yanis',
   'Yoel Bárcenas',
   'Alberto Quintero',
   'Azarías Londoño'],
  'Atacantes': ['Ismael Díaz',
   'Cecilio Waterman',
   'José Fajardo',
   'Tomás Rodríguez']}}