dict_pais_bandeira = {
    'Inglaterra': 'gb-eng',
    'Suíça': 'ch',
    'Colômbia': 'co',
    'Uruguai': 'uy',
    'Costa do Marfim': 'ci',
    'Argentina': 'ar',
    'México': 'mx',
    'Tunísia': 'tn',
    'Turquia': 'tr',
    'África do Sul': 'za',
    'Canadá': 'ca',
    'Cabo Verde': 'cv',
    'Jordânia': 'jo',
    'Catar': 'qa',
    'Argélia': 'dz',
    'Espanha': 'es',
    'Croácia': 'hr',
    'França': 'fr',
    'Haiti': 'ht',
    'Estados Unidos': 'us',
    'Bósnia': 'ba',
    'Austrália': 'au',
    'Brasil': 'br',
    'Gana': 'gh',
    'Bélgica': 'be',
    'Irã': 'ir',
    'Marrocos': 'ma',
    'Alemanha': 'de',
    'Japão': 'jp',
    'Paraguai': 'py',
    'Panamá': 'pa',
    'Senegal': 'sn',
    'Escócia': 'gb-sct',
    'Coreia do Sul': 'kr',
    'Equador': 'ec',
    'Suécia': 'se',
    'Noruega': 'no',
    'Egito': 'eg',
    'Uzbequistão': 'uz',
    'Arábia Saudita': 'sa',
    'Áustria': 'at',
    'Curaçao': 'cw',
    'Holanda': 'nl',
    'Iraque': 'iq',
    'Nova Zelândia': 'nz',
    'Portugal': 'pt',
    'República Tcheca': 'cz',
    'RD Congo': 'cd'
    }

dias = {
    0: "Segunda",
    1: "Terça",
    2: "Quarta",
    3: "Quinta",
    4: "Sexta",
    5: "Sábado",
    6: "Domingo"
}